version: "3.8"

name: contentapis

services:
  contentservicepython:
    container_name: contentservicepython
    image: magtapptest/contentservicepython:v1
    pull_policy: always
    ports:
      - 8000:8000
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - APP_API_KEY=${APP_API_KEY}
      - BUCKET_NAME=${BUCKET_NAME}
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8000/" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - shared_network



networks:
  shared_network:
    external: true
    name: shared_network